### PR TITLE
feat: payment method identifier

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
See also https://github.com/justmoon/koa-ilp/pull/6 and https://github.com/justmoon/superagent-ilp/pull/1

**Review by adrianhopebailie — APPROVED** [review]

**Comment by michielbdejong** [comment]
Will merge as soon as the two dependencies have both been merged. We should also update the rfc.

**Comment by sharafian** [comment]
This is breaking on all of our repos and tools that use HTTP-ILP. Is there any way that we can do it nonbreakingly? What if we changed it from `Pay` to `Pay-Request` and had Koa-ILP return both, and then make it so that the client tools will take `Pay-Request` if it's there and otherwise fall back on `Pay`.

**Review by sharafian — CHANGES_REQUESTED** [review]
This is breaking on all of our repos and tools that use HTTP-ILP. Is there any way that we can do it nonbreakingly? What if we changed it from `Pay` to `Pay-Request`. Koa-ILP could return both, and then we could make it so that the client tools will take `Pay-Request` if it's there and otherwise fall back on `Pay`.

**Comment by michielbdejong** [comment]
Right, that puts me as a tutorial writer in a difficult position, because now on the one hand I want to describe how the `Pay` header works according to the [discussion that Adrian and others at the IETF are having about it](https://lists.w3.org/Archives/Public/ietf-http-wg/2017OctDec/0118.html), and on the other hand, I want the code that Ben and Stefan wrote to be usable. if you want to avoid a breaking change then you need to convince the IETF (or Adrian who is the Internet Draft author) that your current implementation is better.

I guess the only diplomatic option now is to describe both in the tutorials, for the time being. I hope that soon either the internet-draft will update to match what is implemented, or the implementation will update to match what was described and submitted to IETF.

**Comment by michielbdejong** [comment]
Continued in #23.

**Pull request closed without merging**
