### PR TITLE
fix: hyperlinks between tutorials

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
Have you tested these in the rendered website? That's where they need to work the most.

i.e. If these pages are hosted at https://interledger.org/tutorials with a base of https://interledger.org I think they will break

**Comment by michielbdejong** [comment]
I didn't test them on a rendered site but I did notice that if you click the link in the first paragraph of https://interledger.org/tutorials/http-ilp/ it is now broken, and so this will at least not make it worse.

**Comment by michielbdejong** [comment]
Pushed it to https://michielbdejong.github.io/tutorials/hosted-ledgers/ - works there.

**Comment by michielbdejong** [comment]
@adrianhopebailie Can this be merged now?

**Review by adrianhopebailie — APPROVED** [review]
Hard to test but this looks like it should work.

**Comment by michielbdejong** [comment]
Just confirmed that on the live site, the issue identified in https://github.com/interledger/tutorials/pull/28#issuecomment-343604975 is now fixed. Thanks!

**Pull request merged**
