### PR TITLE
Docs: change streaming payments tutorial to http

### PR DESCRIPTION
**Pull request by sharafian**
Gives an introduction to HTTP ILP and shows how to use the developer tools `koa-ilp` and `ilp-curl`

### CODE REVIEW

**Review by michielbdejong — CHANGES_REQUESTED** [review]
I feel this tutorial is too much focused on developer skills (use of tools) and too little on understanding the concepts and bigger picture. It introduces PSK and trustlines (balance at the shop) without explaining those two concepts. I think the way to fix this is to call this tutorial something like 'tooling' and put it after the streaming-payments and trustlines tutorials. What do you think?

**Comment by adrianhopebailie** [comment]
I think we can keep this as HTP-ILP but I recommend the following:

1. Merge the HTTP ILP spec!
2. Consider another tutorial that introduces PSK and trustlines

I don't think we should hold back on making tutorials available unless they are actually teaching something that is wrong.

**Review by adrianhopebailie — APPROVED** [review]
I would recommend we move each tutorial into it's own folder to allow this collection to grow and avoid conflicts.

I'm happy to give this a similar "once-over" once it's merged, in the same way I did with the letter shop to align the style of the tutorials

**Comment by sharafian** [comment]
> It introduces PSK and trustlines (balance at the shop) without explaining those two concepts.

Technically the koa-ilp balances aren't trustlines, because they're controlled unilaterally and are disconnected from the ILP payment flow (adjustments are unconditional). But I see your point.

My main concern with the streaming payments tutorial is that it introduces an unusual implementation of HTTP-ILP and might cause confusion between HTTP-ILP and streaming payments. I think if the streaming payments tutorial were more focused on explaining PSK (which is definitely complicated enough to warrant its own tutorial), we could then move on to the tooling tutorial which shows how to put what they've learned together

**Comment by michielbdejong** [comment]
> an unusual implementation of HTTP-ILP

so far, nothing about HTTP-ILP is "usual", as we're still in the process of defining it :)

I think we need both one-shot and streaming HTTP-ILP make sense, as do both paying exactly the required amount and establishing prepaid balance. Let's have that discussion on Monday, so we can establish what we want HTTP-ILP to look like.

Once we know that, we probably want to teach all of it for both shop implementers and client implementers. I think we need a mix of showing how to use the tools and showing how it actually works under the hood. That doesn't mean discussing the entire PSK spec, just explaining that we use hmac to derive multiple hashlocks from a single shared secret.

**Comment by michielbdejong** [comment]
I rebased this so that it adds the http-ilp tutorial into a folder, and does not delete the streaming-payments tutorial: #15

**Comment by michielbdejong** [comment]
merged in #15

**Pull request closed without merging**
